# Generated by Django 4.0.5 on 2022-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('stop_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
            ],
        ),
    ]
