# Generated by Django 4.0.5 on 2022-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_lat', models.FloatField(blank=True, null=True)),
                ('stop_long', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stops',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BusStation',
        ),
    ]
