# Generated by Django 3.2.4 on 2022-07-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favoritestops',
            table='FavoriteStops',
        ),
    ]
