# Generated by Django 3.2.4 on 2022-07-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapp', '0002_stops_delete_busstation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stops',
            options={'managed': True},
        ),
    ]
