# Generated by Django 3.2.4 on 2022-07-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapp', '0002_alter_favoritestops_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
