# Generated by Django 3.2.4 on 2022-07-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapp', '0003_alter_stops_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stops',
            options={'managed': False},
        ),
    ]
