# Generated by Django 3.2.4 on 2022-07-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapp', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
