# Generated by Django 3.2.4 on 2022-07-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapp', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
