# Generated by Django 3.2.4 on 2022-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapp', '0008_auto_20220726_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account1',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=7),
        ),
    ]
