# Generated by Django 3.2.4 on 2022-07-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dublinbusapp', '0009_alter_account1_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account1',
            name='Favorites',
            field=models.CharField(default='', max_length=30),
        ),
    ]
